### ISSUE TITLE
Code Error in 4_container_images.sh

### ISSUE THREAD

**Issue by maddin58** [containers/podman-security-bench#13]
https://github.com/containers/podman-security-bench/blob/8dbf9170b13733ebd4d4da7c9daa3fe546e8b3ad/tests/4_container_images.sh#L93

mapfile -t packages < "$(podman exec "$c" $listCommand 2>/dev/null)"

**Comment by fluidum** [comment]
_Ubuntu 22.04.2
podman version 4.5.1 (manually installed)_

I just got same error when tried first run script with sh like readme.md describes.

`sudo sh podman-security-bench.sh`
`podman-security-bench.sh: 93: ./tests/4_container_images.sh: Syntax error: redirection unexpected
`

As a solution for me `sudo bash podman-security-bench.sh` ran successfully.

**Comment by ember91** [comment]
This can be closed due to #17
