### ISSUE TITLE
Code Error in 4_container_images.sh

### ISSUE THREAD

**Issue by maddin58** [containers/podman-security-bench#14]
https://github.com/containers/podman-security-bench/blob/8dbf9170b13733ebd4d4da7c9daa3fe546e8b3ad/tests/4_container_images.sh#L216

mapfile -t containerFiles < "$(podman export "$c" | tar -tv 2>/dev/null | grep -E '^[-rwx].*(s|S).*\s[0-9]' | awk '{print $6}')"

**Comment by ember91** [comment]
This can be closed due to #17
