### ISSUE TITLE
directories referenced

### ISSUE THREAD

**Issue by bekefilaszlo** [containers/podman-security-bench#3]
Podman benchmark (chapter 3) is looking for /etc/podman; /etc/sysconfig/podman; /etc/default/podman directories, but those are not present, at least in my kali linux installation. I did not find those mentioned in the documentation either.
Are these used directories?

**Comment by rhatdan** [comment]
No, would you be interested in opening a PR to remove them?

**Comment by ember91** [comment]
This can be closed
